

name: Deploy Policy Stack


on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

env:
  mgName: MG-SCC-Common
  location: uksouth

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  actions: read # Required if repo is private
  contents: read # Required if repo is private
  security-events: write # Required for code scanning

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Bicep
      uses: anthony-c-martin/setup-bicep@v0.3
    
    - name: Bicep Linting
      uses: maikvandergaag/action-biceplint@v1.0.0
      with:
        allfiles: true
        create-sarif: true
        markdown-report: false
        sarif-output-path: bicep-lint.sarif
        markdown-output-path: bicep-lint.md

    - name: Upload SARIF file
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: bicep-lint.sarif
        category: bicep-linting

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        allow-no-subscriptions: true
        enable-AzPSSession: true
    
    - name: Deploy
      uses: azure/powershell@v2
      with:
        azPSVersion: latest
        inlineScript: |
          New-AzManagementGroupDeploymentStack -Name cafFoundationStackDeploy -ManagementGroupId ${{env.mgName}} -Location ${{env.location}} -TemplateFile ./Bicep/cafFoundation.bicep -TemplateParameterFile ./Bicep/cafFoundation.bicepparam -ActionOnUnmanage deleteResources -DenySettingsMode None -Force
          New-AzManagementGroupDeploymentStack -Name tagPolicyStackDeploy -ManagementGroupId ${{env.mgName}} -Location ${{env.location}} -TemplateFile ./Bicep/taggingPolicies.bicep -TemplateParameterFile ./Bicep/taggingPolicies.bicepparam -ActionOnUnmanage deleteResources -DenySettingsMode None -Force
          New-AzManagementGroupDeploymentStack -Name guestConfStackDeploy -ManagementGroupId ${{env.mgName}} -Location ${{env.location}} -TemplateFile ./Bicep/GuestConfiguration.bicep -ActionOnUnmanage deleteResources -DenySettingsMode None -Force

